# Generated by Django 5.2.5 on 2025-08-13 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DynamicField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("int", "Int"),
                            ("float", "Float"),
                            ("string", "String"),
                        ],
                        max_length=20,
                    ),
                ),
                ("order", models.PositiveIntegerField()),
            ],
        ),
    ]
