# Generated by Django 5.2.5 on 2025-08-13 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dynamic_form", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dynamicfield",
            name="field_type",
            field=models.CharField(
                choices=[("int", "Int"), ("float", "Float"), ("str", "String")],
                max_length=20,
            ),
        ),
    ]
